[package]
name = "voxels"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
glfw = "0.58.0"
log = "0.4.22"
image = "0.19.0"
ultraviolet = "0.9.2"
rand = "0.9.0-alpha.2"
fastnoise-lite = "1.1.1"
